openapi: 3.0.0
info:
  title: Jobs API
  version: 1.0.0
paths:
  /api/v1/auth/login:
    post:
      summary: Login and get token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
  /api/v1/jobs:
    get:
      summary: Get all jobs (requires auth)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of jobs
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
